repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types_or: [ts, tsx, javascript, jsx, json, css, markdown]
        additional_dependencies: ["prettier@3", "prettier-plugin-tailwindcss"]

      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: node
        types_or: [ts, tsx]
